version: "3.7"
services:
  clientnode:
    image: divyeshradadiya/helpinghand-forntend:latest
    ports:
      - "3000:3000"
    depends_on:
      - "servernode"
    environment:
      REACT_APP_BASE_API: "ec2-44-200-131-220.compute-1.amazonaws.com"
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.5

  servernode:
    image: divyeshradadiya/helpinghand-backend:latest
    ports:
      - "8081:8081"
    depends_on:
      - "dbnode"
    environment:
      MYSQL_HOST: "dbnode"
      MYSQL_PORT: "3306"
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.6
  dbnode:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - /home/divyesh/myFol/dbnode:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HelpingHand
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.7

networks:
  net_ubuntu:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24