---
- name: Pull and Run docker images from divyeshradadiya/
  hosts: AWS
  tasks:
    - name: copy docker compose file from folder to remote host
      copy:
          src: ./docker-compose.yml
          dest: ./

    - name: sudo pull images specifed in docker-compose
      command: sudo docker-compose -f ./docker-compose.yml pull

    - name: run the pulled docker images in detached mode
      command: sudo docker-compose -f ./docker-compose.yml up -d